name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore CMP186-WorkshopGitHubAction.sln
    - name: Build
      run: dotnet build --no-restore
    - name: Test
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: myartifact
        path: /home/runner/work/GitWorkShop/GitWorkShop/CMP186-WorkshopGitHubAction/bin/Debug/net5.0/publish/
        run: dotnet test --no-build --verbosity normal CMP186-WorkshopGitHubAction.sln
 
